<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Operator;

class OperatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Prepaid-Mobile Operators
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "AT", "OperatorName" => "Airtel"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "VF", "OperatorName" => "VodafoneIdea"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "BSNL", "OperatorName" => "BSNL TopUp"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "BSV", "OperatorName" => "BSNL Recharge/Validity (RCV)"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "BSG", "OperatorName" => "BSNL 3G"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "BSS", "OperatorName" => "BSNL Special (STV)"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "VI", "OperatorName" => "VI"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "ATX", "OperatorName" => "Airtel Express"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "MM", "OperatorName" => "MTNL Mumbai"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "MMS", "OperatorName" => "MTNL Mumbai Special"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "MD", "OperatorName" => "MTNL Delhi"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "MDS", "OperatorName" => "MTNL Delhi Special"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "JIO", "OperatorName" => "Reliance Jio"],
            ["ServiceTypeName" => "Prepaid-Mobile", "OperatorCode" => "JIOX", "OperatorName" => "JIO Express"],

            // Broadband Operators
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "TBB", "OperatorName" => "Tikona Infinet Pvt Ltd"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "HBB", "OperatorName" => "Hathway Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "CBB", "OperatorName" => "Connect Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "AFB", "OperatorName" => "ACT Fibernet"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "TTB", "OperatorName" => "TTN BroadBand"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "SBB", "OperatorName" => "Spectra"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "NBB", "OperatorName" => "NEXTRA BB"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "CWB", "OperatorName" => "Comway Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "FBB", "OperatorName" => "Fusionnet Web Services Private Limited"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "DEB", "OperatorName" => "DEN Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "MNB", "OperatorName" => "M-NET Fiber Fast"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "TIB", "OperatorName" => "Timbl Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "ONB", "OperatorName" => "ION"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "VFB", "OperatorName" => "Vfibernet Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "ILB", "OperatorName" => "Instalinks"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "NB", "OperatorName" => "Netplus Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "EB", "OperatorName" => "Excell Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "FF", "OperatorName" => "Flash Fibernet"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "ABSPL", "OperatorName" => "Alliance Broadband Services Pvt. Ltd."],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "A-RB", "OperatorName" => "AirJaldi - Rural Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "KRLVBPL", "OperatorName" => "Kerala Vision Broadband"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "MICIPLBP", "OperatorName" => "Microscan Infocommtech Pvt. Ltd."],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "LimrasBP", "OperatorName" => "Blue Lotus Support Services Pvt ltd"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "DWANBP", "OperatorName" => "DWAN Supports Private Ltd"],
            ["ServiceTypeName" => "Broadband", "OperatorCode" => "LinkioBP", "OperatorName" => "Linkio Fibernet"],
             //DTH
            ["ServiceTypeName" => "DTH", "OperatorCode" => "DTD", "OperatorName" => "Dish TV"],
            ["ServiceTypeName" => "DTH", "OperatorCode" => "TSD", "OperatorName" => "Tata Play"],
            ["ServiceTypeName" => "DTH", "OperatorCode" => "VDD", "OperatorName" => "Videocon DTH"],
            ["ServiceTypeName" => "DTH", "OperatorCode" => "SD", "OperatorName" => "Sun Direct"],
            ["ServiceTypeName" => "DTH", "OperatorCode" => "ATD", "OperatorName" => "Airtel Digital TV"],
            ["ServiceTypeName" => "DTH", "OperatorCode" => "IND11998", "OperatorName" => "Sun Direct TV (Flexi Plans)"],
              //Landline Postpaid
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "MDL", "OperatorName" => "MTNL Delhi"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "ATL", "OperatorName" => "Airtel Landline"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "MML", "OperatorName" => "MTNL Mumbai"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "TDCLE", "OperatorName" => "Tata Teleservices"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "ATLFP", "OperatorName" => "Airtel Landline (Fetch and Pay)"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "Bl-C", "OperatorName" => "BSNL Landline - Corporate"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "Bl-I", "OperatorName" => "BSNL Landline - Individual"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "MTNLMLP", "OperatorName" => "MTNL Mumbai (Multiple Bills)"],
            ["ServiceTypeName" => "Landline Postpaid", "OperatorCode" => "IND11207", "OperatorName" => "MTNL Mumbai Lease Circuit"],
            
            //ELECTRICITY
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "BRP", "OperatorName" => "BSES Rajdhani Power Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "BYP", "OperatorName" => "BSES Yamuna Power Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "TPD", "OperatorName" => "Tata Power - Delhi"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "NBELE", "OperatorName" => "North Bihar Power Distribution Company Ltd."],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "SBELE", "OperatorName" => "South Bihar Power Distribution Company Ltd."],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "BEMUM", "OperatorName" => "B.E.S.T Mumbai"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "TP", "OperatorName" => "Torrent Power"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "UHBV", "OperatorName" => "Uttar Haryana Bijli Vitran Nigam (UHBVN)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "CEB", "OperatorName" => "Chhattisgarh State Power Distribution Co. Ltd"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "DGVCL", "OperatorName" => "Dakshin Gujarat Vij Company Limited (DGVCL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "MGVC", "OperatorName" => "Madhya Gujarat Vij Company Limited (MGVCL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "PGVC", "OperatorName" => "Paschim Gujarat Vij Company Limited (PGVCL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "TNEB", "OperatorName" => "Tamil Nadu Electricity Board (TNEB)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "UGVC", "OperatorName" => "Uttar Gujarat Vij Company Limited (UGVCL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "AVVN", "OperatorName" => "Ajmer Vidyut Vitran Nigam Limited (AVVNL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "JVVNL", "OperatorName" => "Jaipur Vidyut Vitran Nigam (JVVNL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "BESCOM", "OperatorName" => "Bangalore Electricity Supply Co. Ltd (BESCOM)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "JOVVNL", "OperatorName" => "Jodhpur Vidyut Vitran Nigam Limited (JDVVNL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "MSEDCL", "OperatorName" => "Maharashtra State Electricity Distbn Co Ltd"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "MPMKVVCL", "OperatorName" => "M.P. Madhya Kshetra Vidyut Vitaran - URBAN"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "NPCL", "OperatorName" => "Noida Power"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "MPPKVI", "OperatorName" => "M.P. Paschim Kshetra Vidyut Vitaran"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "JUSCL", "OperatorName" => "Jamshedpur Utilities"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "TSEC", "OperatorName" => "Tripura Electricity Corp Ltd"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "PSPCL", "OperatorName" => "Punjab State Power Corporation Ltd (PSPCL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "BPE", "OperatorName" => "Bharatpur Electricity Services Ltd. (BESL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "BKE", "OperatorName" => "Bikaner Electricity Supply Limited (BkESL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "CWE", "OperatorName" => "CESC Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "DHE", "OperatorName" => "Dakshin Haryana Bijli Vitran Nigam (DHBVN)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "GKE", "OperatorName" => "Gulbarga Electricity Supply Company Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "KRE", "OperatorName" => "Kota Electricity Distribution Limited (KEDL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "MEE", "OperatorName" => "Meghalaya Power Dist Corp Ltd"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "NOE", "OperatorName" => "TP Northern Odisha Distribution Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "SOE", "OperatorName" => "TP Southern Odisha Distribution Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "TME", "OperatorName" => "Tata Power - Mumbai"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "AJE", "OperatorName" => "TP Ajmer Distribution Ltd (TPADL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "WOE", "OperatorName" => "TP Western Odisha Distribution Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "ANE", "OperatorName" => "Assam Power Distribution Company Ltd (NON-RAPDR)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "CKE", "OperatorName" => "Chamundeshwari Electricity Supply Corp Ltd (CESCOM)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "HKE", "OperatorName" => "Hubli Electricity Supply Company Ltd (HESCOM)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "HPE", "OperatorName" => "Himachal Pradesh State Electricity Board"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "JBE", "OperatorName" => "Jharkhand Bijli Vitran Nigam Limited (JBVNL)"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "MPMKUVCL", "OperatorName" => "M.P. Madhya Kshetra Vidyut Vitaran - RURAL"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "MMMRVCL", "OperatorName" => "M.P. Poorv Kshetra Vidyut Vitaran - RURAL"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "SKE", "OperatorName" => "Sikkim Power - RURAL"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "NME", "OperatorName" => "New Delhi Municipal Council (NDMC) - Electricity"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "KUE", "OperatorName" => "Kanpur Electricity Supply Company"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "AME", "OperatorName" => "Adani Electricity Mumbai Limited"],
            ["ServiceTypeName" => "Electricity", "OperatorCode" => "KSE", "OperatorName" => "Kerala State Electricity Board Ltd. (KSEBL)"],
             //GAS
            ["ServiceTypeName" => "GAS", "OperatorCode" => "MMG", "OperatorName" => "Mahanagar Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "GGCO", "OperatorName" => "Gujarat Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "ING", "OperatorName" => "Indraprastha Gas"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "ADG", "OperatorName" => "Adani Total Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "HCG", "OperatorName" => "Haryana City Gas Distribution Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "SGG", "OperatorName" => "Sabarmati Gas Limited (SGL)"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "TNG", "OperatorName" => "Tripura Natural Gas"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "UCG", "OperatorName" => "Unique Central Piped Gases Pvt Ltd (UCPGPL)"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "VGG", "OperatorName" => "Vadodara Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "MNG", "OperatorName" => "Maharashtra Natural Gas Limited (MNGL)"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "AVG", "OperatorName" => "Aavantika Gas Ltd."],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "CUG", "OperatorName" => "Central U.P. Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "CGG", "OperatorName" => "Charotar Gas Sahakari Mandali Ltd"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IAG", "OperatorName" => "Indian Oil-Adani Gas Private Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "AGG", "OperatorName" => "Assam Gas Company Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "GGG", "OperatorName" => "Green Gas Limited(GGL)"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IRG", "OperatorName" => "IRM Energy Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "GGLD", "OperatorName" => "GAIL Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "BNGLD", "OperatorName" => "Bhagyanagar Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "MG", "OperatorName" => "Megha Gas"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "NGPL", "OperatorName" => "Naveriya Gas Pvt Ltd"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "GIL", "OperatorName" => "GAIL India Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "INDOILGAS", "OperatorName" => "Indian Oil Corporation Ltd-Piped Gas"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND11064", "OperatorName" => "Purba Bharati Gas Pvt Ltd"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND11267", "OperatorName" => "HP Oil Gas Private Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND11323", "OperatorName" => "Hindustan Petroleum Corporation Ltd-Piped Gas"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND11413", "OperatorName" => "AGP CGD India Pvt Ltd"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND11414", "OperatorName" => "AGP City Gas Pvt Ltd"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND11507", "OperatorName" => "Godavari Gas Pvt Ltd"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND12277", "OperatorName" => "Bengal Gas Company Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND12285", "OperatorName" => "Think Gas"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND12407", "OperatorName" => "Goa Natural Gas Private Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND29187", "OperatorName" => "Haryana City Gas Distribution Bhiwadi Ltd"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND29188", "OperatorName" => "Rajasthan State Gas Limited"],
            ["ServiceTypeName" => "GAS", "OperatorCode" => "IND29189", "OperatorName" => "Torrent Gas"],
            //Insurance
            
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "LIC", "OperatorName" => "Life Insurance Corporation of India"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "BALICL", "OperatorName" => "Bajaj Allianz Life Insurance Company Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "ALI", "OperatorName" => "Bandhan Life Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "RGICL", "OperatorName" => "Reliance General Insurance Company Limited (Motor)"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "MH-HI", "OperatorName" => "Magma HDI - Health Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "MBHI", "OperatorName" => "Niva Bupa Health Insurance Company Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "RSGICL", "OperatorName" => "Royal Sundaram General Insurance Co. Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "MH-LI", "OperatorName" => "Magma HDI - Non Motor Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "MH-MI", "OperatorName" => "Magma HDI - Motor Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "AVLI", "OperatorName" => "Aviva Life Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "BAGI", "OperatorName" => "Bajaj Allianz General Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "CHOLI", "OperatorName" => "Canara HSBC Life Insurance Co Ltd"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "MLICL", "OperatorName" => "Max Life Insurance Company Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "ABHICL", "OperatorName" => "Aditya Birla Health Insurance Co Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "AFLICL", "OperatorName" => "Ageas Federal Life Insurance Company Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IPLI-N", "OperatorName" => "ICICI Prudential Life Insurance Renewal"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10749", "OperatorName" => "HDFC Life Insurance (for Former Exide Life Customers only)"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10780", "OperatorName" => "Pramerica Life Insurance Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "ICICILGI", "OperatorName" => "ICICI Lombard General Insurance (Motor)"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "INDIAFLIC", "OperatorName" => "IndiaFirst Life Insurance Company Ltd"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "GODGIL", "OperatorName" => "Go Digit Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "RHINS", "OperatorName" => "Reliance General Insurance Company Limited (Health)"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10835", "OperatorName" => "Shriram Life Insurance Co. Ltd."],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "ABSLII", "OperatorName" => "Aditya Birla Sun Life Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IFFTGICI", "OperatorName" => "Iffco Tokio General Insurance Company Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "FGILII", "OperatorName" => "Future Generali India Life Insurance Company Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "SUDILII", "OperatorName" => "Star Union Dai Ichi Life Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "HLII", "OperatorName" => "HDFC Life Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "BAXALII", "OperatorName" => "BHARTI AXA Life Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10913", "OperatorName" => "ManipalCigna Health Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10927", "OperatorName" => "The Oriental Insurance Company Limited"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10941", "OperatorName" => "Star Health And Allied Insurance Company"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10959", "OperatorName" => "Shriram General Insurance - Quote Payment"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND10990", "OperatorName" => "ICICI Lombard General Insurance (Health)"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11338", "OperatorName" => "TATA AIG General Insurance co. Ltd Retail"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11455", "OperatorName" => "HDFC ERGO General Insurance (Motor)"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11502", "OperatorName" => "Acko General Insurance Health"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11503", "OperatorName" => "Acko General Insurance Motor"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11513", "OperatorName" => "SBI General Health Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11514", "OperatorName" => "SBI General Motor Insurance"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11519", "OperatorName" => "Bajaj Finance Ltd - Corporate agent"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11526", "OperatorName" => "Pnb Metlife India Insurance Company Ltd"],
            ["ServiceTypeName" => "Insurance", "OperatorCode" => "IND11540", "OperatorName" => "Future Generali India Insurance Co Ltd-General Insurance"],
            //DMR
            ["ServiceTypeName" => "DMR", "OperatorCode" => "DMR", "OperatorName" => "Money Transfer (Domestic)"],
            
            //water
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29154", "OperatorName" => "Chennai Metropolitan Water Supply And Sewerage Board"],
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29155", "OperatorName" => "DDA - (East Zone)"],
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29156", "OperatorName" => "Grampanchayat Aitawade Khurd Water"],
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29157", "OperatorName" => "Municipal Corporation of Gurugram (MCG) - Water"],
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29158", "OperatorName" => "Nagar Nigam Aligarh - Water"],
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29159", "OperatorName" => "Public Health Engineering Department, Haryana"],
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29160", "OperatorName" => "Punjab Municipal Corporations Councils Sewerage"],
            ["ServiceTypeName" => "Water", "OperatorCode" => "IND29161", "OperatorName" => "Thane Municipal Corporation Water Tax"],
            ["ServiceTypeName" => "PAN UTI - Token Based", "OperatorCode" => "PAN", "OperatorName" => "PAN Application (UTI)"],
            //
        ];

        foreach ($data as $item) {
            Operator::updateOrCreate(
                [
                    'ServiceTypeName' => $item['ServiceTypeName'],
                    'OperatorCode' => $item['OperatorCode'],
                ],
                ['OperatorName' => $item['OperatorName']]
            );
        }
    }
}
